// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpirkglqolxukfgghtfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwaXJrZ2xxb2x4dWtmZ2dodGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODIyNzUsImV4cCI6MjA2Mjg1ODI3NX0.pu7bZzhpCN0Jc6E0JHo_VQRQXzdF6aOS9KwPw-yDzvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);